// todo-vue/src/TodoList.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getTodos, type Todo } from './Todo'

let todos = ref<Todo[]>([])

onMounted(async () => {
  todos.value = await getTodos()
  sort()
})

const sort = () => {
  todos.value = todos.value.sort((a, b) => (a.completed ? 1 : -1))
}
</script>

<template>
  <div v-if="todos.length === 0">Patienter ....</div>
  <p v-else>
    Completed : {{ todos.filter(t => t.completed).length }} / {{ todos.length }}
  </p>
  <ul>
    <li
      :class="{ completed: todo.completed }"
      v-for="todo in todos"
      :key="todo.id"
    >
      <label>
        <input type="checkbox" v-model="todo.completed" @change="sort" />
        <span>{{ todo.title }}</span>
      </label>
    </li>
  </ul>
</template>

<style>
.completed {
  text-decoration: line-through;
}
</style>

// react-todo/src/TodoList.jsx
import { useEffect, useState } from "react";
import TodoService from "./TodosService";
import TodoItem from "./TodoItem";

export default function TodoList() {
  let [todos, setTodos] = useState([]);

  useEffect(() => {
    TodoService.getTodos().then((data) => setTodos(data));
  }, []);

  return (
    <>
      <div>
        Completed ({todos.filter((todo) => todo.completed).length}/
        {todos.length})
      </div>
      <ul>
        {todos
          .sort((a, b) => (a.completed ? 1 : -1))
          .map((todo) => (
            <TodoItem
              key={todo.id}
              todo={todo}
              onChange={(e) => {
                todo.completed = e.target.checked;
                setTodos([...todos]);
              }}
            />
          ))}
      </ul>
    </>
  );
}
